// Generates the three AEGIS402 testnet accounts and writes .env
// Run once: node scripts/keygen.mjs
import algosdk from "algosdk";
import { writeFileSync, existsSync } from "node:fs";

const ROLES = [
  ["AGENT", "the AI agent's vault — pays for services, target of the jailbreak attack"],
  ["MERCHANT", "the legitimate x402 resource server — allowlisted receiver"],
  ["ATTACKER", "the attacker's address — NOT allowlisted, must never receive funds"],
];

if (existsSync(".env")) {
  console.error("REFUSING: .env already exists. Delete it first if you really want new keys.");
  process.exit(1);
}

const lines = ["# AEGIS402 testnet accounts — generated by scripts/keygen.mjs", "# TESTNET ONLY. Never put mainnet keys in this file.", ""];
const summary = [];

for (const [role, desc] of ROLES) {
  const acct = algosdk.generateAccount();
  const mnemonic = algosdk.secretKeyToMnemonic(acct.sk);
  // @x402/avm expects base64 of the full 64-byte key (32-byte seed + 32-byte pubkey)
  const privateKeyB64 = Buffer.from(acct.sk).toString("base64");
  lines.push(`# ${role}: ${desc}`);
  lines.push(`${role}_ADDRESS=${acct.addr}`);
  lines.push(`${role}_MNEMONIC="${mnemonic}"`);
  lines.push(`${role}_PRIVATE_KEY_B64=${privateKeyB64}`);
  lines.push("");
  summary.push({ role, address: acct.addr.toString() });
}

lines.push("# Network");
lines.push("ALGOD_URL=https://testnet-api.algonode.cloud");
lines.push("INDEXER_URL=https://testnet-idx.algonode.cloud");
lines.push("USDC_ASA_ID=10458941");
lines.push("FACILITATOR_URL=https://facilitator.goplausible.xyz");
lines.push("");

writeFileSync(".env", lines.join("\n"));

console.log("\n=== AEGIS402 TESTNET ACCOUNTS (written to .env) ===\n");
for (const s of summary) console.log(`${s.role.padEnd(9)} ${s.address}`);
console.log("\nFund AGENT + MERCHANT with ALGO:  https://lora.algokit.io/testnet/fund");
console.log("Fund AGENT with testnet USDC:    https://faucet.circle.com  (select Algorand Testnet)");
console.log("(ATTACKER needs no funding — it only ever receives, and must never succeed.)\n");
